---
title: "Introduction | Results | Conclusion"
author: "Paola Bojorquez-Ramirez"
date: "12/16/2022"
---
# Introduction 

Hello, here you will find my introduction, results, and conclusionfor my BST 260 project on this tab. Figures and references (without code) can be found in the second tab. 


# Where is the data used for this project from?

The Mother’s Significant Feature (MSF) dataset contains data collected from 450 mothers from the Mumbai metropolitan region in Maharashtra, India interviewed after childbirth between February 2018 to March 2021.^1^ It is composed of 130 variables (i.e. attributes) that cover a range of descriptive to health-related outcomes for mothers and fathers across 6 Excel spreadsheets. The dataset was designed to provide data for researchers to conduct analyses that will contribute to improved reproductive and health outcomes among mothers, fathers, and children. It consists of common factors and health outcomes experienced across the following three major reproductive phases relevant to this population: late adolescence, post-marriage, and during pregnancy. The 130 attributes were selected based on literature reviews and brainstorming sessions with gynecologists and pediatricians. They are organized into the following main five categories: physical, social, lifestyle, stress levels, and health outcomes. Each of the 450 mothers included in the dataset were assigned a unique ID number included in the “Mother_UID” variable which was used used to merge relevant csv files.

# What is the objective of this project and why does it matter?

Preterm deliveries are the leading cause of death in children under 5 years across the world, with approximately 20% of the 15 million babies born preterm globally occurring in India.^2^ Studies have shown that preterm delivery is less common among women with good glycemic control.^3^ Moreover, observational studies have corroborated that risks for preterm delivery are multifactorial and cannot be deduced to solely biological mechanisms. Given the inherent need to identify factors that may be associated with higher odds of preterm deliveries, the main objective of this project was to assess the association between preterm deliveries and gestational diabetes, infertility treatment, and hypertension during pregnancy. 

To assess whether there are significant associations between the respective binary variables, Fisher’s Exact and Chi-Square association tests were conducted along with odds ratios and confidence intervals. These tests were warranted because 1) each of the three respective pairs of associations were binary, 2) all 450 mothers in the dataset are independent observations, and 3) cells in the 2x2 contingency tables are mutually exclusive. The Chi-Square test of independence assumes that the expected values for each cell in 2x2 contingency tables are 5 or greater. This assumption was not met for 2 of the associations of interest. Despite the sum of the rows and columns not being fixed and following a hypergeometric distribution, a Fisher’s Exact test was performed because applying the approximation method from a Chi-squared test was not appropriate. Statistical theory states that for large enough 2x2 cell entries, the log of the odds ratio is approximately normal and a confidence interval can be constructed. Although the overall sample size of 450 is large, multiple cell values in the contingency table are smaller than 10 so asymptotics may not hold. Because of the small cell sizes, confidence intervals are expected to be wide.

# Results

Table 1 summarizes continuous and categorical demographic and health variables among mothers with and without gestational diabetes. There were a total of 11 and 439 with and without gestational diabetes in the study population. Women with gestational diabetes were on average older (28.6 years vs 26.6 years) and had a higher BMI (25.7 vs 23.2) than women without gestational diabetes. The family income and education variables are non-informative in this example because a codebook describing what each discrete category represents is not publicly available online. The variables were kept in the Table because these are potential confounders that one would want to adjust for in adjusted analyses such a binomial generalized linear model. Interestingly, all women with gestational diabetes did not have hypertension while a greater percentage reported a preterm delivery (63.6%) compared to no preterm delivery (36.4%). Among women with gestational diabetes, 81.8% reported no history of infertility treatment.

To highlight one of the predictor-outcome associations, Figure 1 was created to show the number of preterm deliveries by gestational diabetes in a stacked barplot. Table 1 and Figure 1 show that the percentage of preterm deliveries among women with gestational diabetes (63.6%) was greater than the percentage of preterm deliveries observed among women without gestational diabetes (16.9%). These visualizations indicate that the presence of gestational diabetes may be associated with preterm deliveries. 

Each of the associations of interest are summarized in 2x2 contingency tables. Table 2 shows the observed occurrences in each of the four cells for preterm deliveries and gestational diabetes with column percentages. Similar information is presented in Figure 2 in a Mosaic plot which shows each combination of variables represented by a rectangle. The size of the rectangle is proportional to the number of individuals in that combination compared to the total study population. For instance, the majority of mothers in this study population that do not have gestational diabetes also do not report delivering a baby preterm. Since this association did not meet the expected cell counts assumption needed to run a Chi-squared test of independence,  Fisher’s Exact test was conducted. According to a p-value less than 0.001, we reject the null hypothesis and conclude there is a statistically significant association between gestational diabetes and preterm delivery. The calculated odds ratio from this study population indicates that the odds of preterm delivery among women with gestational diabetes is 8.57 times the odds of preterm delivery among mothers without gestational diabetes (95% CI: 2.12, 40.99). Because of the high variability from the  limited observations of gestational diabetes, the estimated confidence interval is not precise.

Table 3 shows the observed occurrences in each of the four cells for preterm deliveries and infertility treatment with column percentages. Unlike Table 2, there is a greater percentage of women without preterm deliveries (67.9 and 82.9%) than preterm deliveries among mothers with and without infertility treatment.  Nonetheless, the percentage of mothers with a preterm birth is greater among mothers with infertility treatment (32.1%) compared to mothers without infertility treatment (17.1%). The Mosaic Plot in Figure 3 shows that the majority of mothers in this study population do not report either infertility treatment or preterm delivery. Since each of the expected cell counts for infertility treatment and preterm delivery are 5 or above, a Chi-squared test for independence was performed. Based on a p-value of 0.079, we conclude there is no sufficient evidence for an association between infertility treatment and preterm delivery. The estimated odds ratio from this study population indicates that the odds of preterm delivery among mothers with infertility treatment is 2.30 times the odds of preterm delivery among mothers without infertility treatment (95% CI: 0.88, 5.59).

Table 4 shows the observed occurrences in each of the four cells for preterm deliveries and hypertension during pregnancy with column percentages. The majority of mothers without hypertension do not report a preterm delivery (83.3%) while a large but not majority of mothers with hypertension report a preterm delivery (45.0%). The mosaic plot in Figure 4, shows that the majority of mothers in this study population did not deliver a baby preterm and do not have hypertension. Since each of the expected cell counts for hypertension and preterm delivery are not at least 5, a Fisher’s Exact test for independence was performed. Based on a p-value of 0.004, we conclude there is a statistically significant association between hypertension and preterm delivery. The estimated odds ratio from this study population indicates that the odds of preterm delivery among mothers with hypertension is 4.05 times the odds of preterm delivery among mothers without hypertension (95% CI: 1.43, 11.20).

# Conclusion
The purpose of this project was to conduct exploratory analyses using the Mother’s Significant Feature dataset and assess whether gestational diabetes, infertility treatment, and hypertension during pregnancy were associated with preterm deliveries among a study population of 450 mothers from the Mumbai metropolitan region in Maharashtra, India who gave birth between February 2018 to March 2021. Fisher’s Exact and Chi-squared test of independence were performed to identify the associations between the aforementioned pairs of binary variables. Odds ratios and 95% confidence intervals were estimated using the Fisher’s Exact test function in R.The study found increased odds of preterm deliveries for mothers with gestational diabetes, hypertension, and infertility treatment but the latter association was not statistically significant.

In light of the limited occurrences of gestational diabetes, hypertension, and infertility treatment history, I do not think my analysis was successful. Because of the large standard deviations from limited information in the dataset, the confidence intervals were wide. Moreover, my interpretation of the descriptive statistics in Table 1 were limited because there is no online codebook to determine what each of the discrete categories for variables with more than two categories mean. If I had more time, I would check for assumptions and perform adjusted logistic regression models to compare to the crude odds calculated in this project. All odds ratios were relatively high and likely biased upwards by common confounders like mother’s age, education, and income. Given that the counts for many of the categories for common demographic variables such as education and income were small, this analysis would require that I know how each categorical variable is coded to collapse categories.
